const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const storeKey='ncp-pro-v1';
const defaultOperatives=[
 {name:'Jamie Dickson',company:'NCP Mechanical',trade:'Supervisor',cscs:''},
 {name:'Elisei Ursescu',company:'NCP Mechanical',trade:'Plumber',cscs:''},
 {name:'Marius Podiuc',company:'NCP Mechanical',trade:'Mechanical Supervisor',cscs:''}
];
let state=JSON.parse(localStorage.getItem(storeKey)||'{}');
state.operatives=state.operatives||defaultOperatives;state.rows=state.rows||[];state.qaRecords=state.qaRecords||[];state.variationRecords=state.variationRecords||[];state.labourRecords=state.labourRecords||[];
function save(){localStorage.setItem(storeKey,JSON.stringify(state));updateKpis();}
function today(){return new Date().toISOString().slice(0,10)}
function timeNow(){return new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}
function switchSection(id){$$('.page').forEach(p=>p.classList.toggle('active',p.id===id));$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.section===id));}
$$('[data-section], [data-section-link]').forEach(b=>b.addEventListener('click',()=>switchSection(b.dataset.section||b.dataset.sectionLink)));
function init(){ $('#briefDate').value=state.briefDate||today();$('#docNo').value=state.docNo||`NCP-DSB-${today().replaceAll('-','')}`;['projectName','mainContractor','siteAddress','siteManager','plannedActivities','locationArea','hsBriefing','deliveries'].forEach(id=>{if(state[id]) $('#'+id).value=state[id];}); if(!state.rows.length)addRow(); renderRows(); renderOperatives(); renderModuleRecords(); populateLabourOperatives(); updateKpis(); }
function operativeOptions(selected=''){return `<option value="">Select operative</option>`+state.operatives.map(o=>`<option ${o.name===selected?'selected':''} value="${escapeHtml(o.name)}">${escapeHtml(o.name)}</option>`).join('')}
function addRow(data={}){state.rows.push({name:data.name||'',company:data.company||'',trade:data.trade||'',cscs:data.cscs||'',time:data.time||'',signature:data.signature||''});save();}
function renderRows(){const body=$('#attendanceBody');body.innerHTML='';state.rows.forEach((r,i)=>{const tr=document.createElement('tr');tr.className=r.signature?'signed':'';tr.innerHTML=`<td>${i+1}</td><td><select data-i="${i}" data-field="name">${operativeOptions(r.name)}</select></td><td><input data-i="${i}" data-field="company" value="${escapeHtml(r.company)}"></td><td><input data-i="${i}" data-field="trade" value="${escapeHtml(r.trade)}"></td><td><input data-i="${i}" data-field="cscs" value="${escapeHtml(r.cscs)}"></td><td><input data-i="${i}" data-field="time" value="${escapeHtml(r.time)}" placeholder="07:15"></td><td class="signature-cell"><button type="button" class="signature-preview" data-sign="${i}">${r.signature?`<img src="${r.signature}" alt="Signature">`:'Tap to sign'}</button>${r.signature?'<div class="signed-badge">Signed</div>':''}</td><td><button type="button" class="remove-row" data-remove="${i}">Remove</button></td>`;body.appendChild(tr);});
 $$('[data-field]').forEach(el=>el.addEventListener('change',e=>{const i=+e.target.dataset.i,field=e.target.dataset.field;state.rows[i][field]=e.target.value;if(field==='name'){const op=state.operatives.find(o=>o.name===e.target.value);if(op){state.rows[i].company=op.company;state.rows[i].trade=op.trade;state.rows[i].cscs=op.cscs; if(!state.rows[i].time)state.rows[i].time=timeNow();}}save();renderRows();}));
 $$('[data-remove]').forEach(b=>b.addEventListener('click',()=>{state.rows.splice(+b.dataset.remove,1);save();renderRows();}));$$('[data-sign]').forEach(b=>b.addEventListener('click',()=>openSignature(+b.dataset.sign)));}
function renderOperatives(){const list=$('#operativeList');list.innerHTML='';state.operatives.forEach((o,i)=>{const d=document.createElement('div');d.className='operative-item';d.innerHTML=`<span><b>${escapeHtml(o.name)}</b> · ${escapeHtml(o.company)} · ${escapeHtml(o.trade)} · ${escapeHtml(o.cscs||'No CSCS')}</span><button class="remove-row" data-op-remove="${i}">Remove</button>`;list.appendChild(d);});$$('[data-op-remove]').forEach(b=>b.addEventListener('click',()=>{state.operatives.splice(+b.dataset.opRemove,1);save();renderOperatives();renderRows();}));}
$('#addOperativeBtn').addEventListener('click',e=>{e.preventDefault();const name=$('#newOperativeName').value.trim();if(!name)return;state.operatives.push({name,company:$('#newOperativeCompany').value.trim(),trade:$('#newOperativeTrade').value.trim(),cscs:$('#newOperativeCscs').value.trim()});['newOperativeName','newOperativeTrade','newOperativeCscs'].forEach(id=>$('#'+id).value='');save();renderOperatives();renderRows();});
$('#addRowBtn').addEventListener('click',()=>{addRow();renderRows();});
$('#clearBriefingBtn').addEventListener('click',()=>{if(confirm('Clear daily briefing form and signatures?')){state.rows=[];save();addRow();renderRows();}});
['briefDate','docNo','projectName','mainContractor','siteAddress','siteManager','plannedActivities','locationArea','hsBriefing','deliveries'].forEach(id=>$('#'+id).addEventListener('input',e=>{state[id]=e.target.value;save();}));
function updateKpis(){const signed=(state.rows||[]).filter(r=>r.signature).length;$('#kpiOperatives').textContent=(state.rows||[]).filter(r=>r.name).length;$('#kpiSigned').textContent=signed;$('#briefingStatus').textContent=signed?`${signed} operative(s) signed today.`:'No signed operatives yet.';}
let activeRow=null,ctx,drawing=false,last=null;
function openSignature(i){activeRow=i;$('#signatureTitle').textContent=`Signature: ${state.rows[i].name||'Operative'}`;const modal=$('#signatureModal');modal.hidden=false;modal.style.display='flex';setTimeout(setupCanvas,50);}
function setupCanvas(){const c=$('#signatureCanvas');const rect=c.getBoundingClientRect();c.width=rect.width*devicePixelRatio;c.height=rect.height*devicePixelRatio;ctx=c.getContext('2d');ctx.scale(devicePixelRatio,devicePixelRatio);ctx.lineWidth=3;ctx.lineCap='round';ctx.strokeStyle='#111';ctx.fillStyle='#fff';ctx.fillRect(0,0,rect.width,rect.height);}
function pos(e){const c=$('#signatureCanvas'),r=c.getBoundingClientRect();const p=e.changedTouches?e.changedTouches[0]:(e.touches?e.touches[0]:e);return{x:p.clientX-r.left,y:p.clientY-r.top}}
function startDraw(e){if(e.cancelable)e.preventDefault();drawing=true;last=pos(e);}
function moveDraw(e){if(!drawing)return;if(e.cancelable)e.preventDefault();const p=pos(e);ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();last=p;}
function endDraw(e){drawing=false;last=null;}
const sigCanvas=$('#signatureCanvas');
sigCanvas.addEventListener('pointerdown',startDraw,{passive:false});
sigCanvas.addEventListener('pointermove',moveDraw,{passive:false});
sigCanvas.addEventListener('pointerup',endDraw,{passive:false});
sigCanvas.addEventListener('pointercancel',endDraw,{passive:false});
sigCanvas.addEventListener('touchstart',startDraw,{passive:false});
sigCanvas.addEventListener('touchmove',moveDraw,{passive:false});
sigCanvas.addEventListener('touchend',endDraw,{passive:false});
sigCanvas.addEventListener('mousedown',startDraw);
sigCanvas.addEventListener('mousemove',moveDraw);
window.addEventListener('mouseup',endDraw);
function stopButtonEvent(e){if(e){e.preventDefault();e.stopPropagation();}}
window.clearSignatureCanvas=function(e){stopButtonEvent(e);drawing=false;setupCanvas();};
window.closeSignatureModal=function(e){stopButtonEvent(e);drawing=false;activeRow=null;const modal=$('#signatureModal');modal.hidden=true;modal.style.display='none';};
window.saveSignatureModal=function(e){stopButtonEvent(e);drawing=false;if(activeRow===null||activeRow===undefined||!state.rows[activeRow]){window.closeSignatureModal(e);return;}const c=$('#signatureCanvas');state.rows[activeRow].signature=c.toDataURL('image/png');if(!state.rows[activeRow].time)state.rows[activeRow].time=timeNow();save();const modal=$('#signatureModal');modal.hidden=true;modal.style.display='none';renderRows();};
function bindActionButton(id,fn){const el=$('#'+id);if(!el)return;['click','touchend','pointerup','mouseup'].forEach(evt=>{el.addEventListener(evt,function(e){fn(e);},{passive:false,capture:true});});}
bindActionButton('clearSignatureBtn',window.clearSignatureCanvas);
bindActionButton('closeSignatureBtn',window.closeSignatureModal);
bindActionButton('saveSignatureBtn',window.saveSignatureModal);
document.addEventListener('click',function(e){const b=e.target.closest && e.target.closest('#closeSignatureBtn,#clearSignatureBtn,#saveSignatureBtn');if(!b)return;if(b.id==='closeSignatureBtn')window.closeSignatureModal(e);if(b.id==='clearSignatureBtn')window.clearSignatureCanvas(e);if(b.id==='saveSignatureBtn')window.saveSignatureModal(e);},true);

function showPanel(id){const el=$(id); if(el){el.hidden=false; el.scrollIntoView({behavior:'smooth',block:'start'});}}
function hidePanel(id){const el=$(id); if(el)el.hidden=true;}
function openNewQa(){switchSection('qa'); $('#qaDate').value=today(); showPanel('#qaFormPanel');}
function openNewVariation(){switchSection('variations'); $('#varDate').value=today(); $('#varNo').value=`NCP-VAR-${String((state.variationRecords||[]).length+1).padStart(3,'0')}`; showPanel('#variationFormPanel');}
function openNewLabour(){switchSection('labour'); $('#labDate').value=today(); populateLabourOperatives(); showPanel('#labourFormPanel');}
['newQaBtn','newQaTopBtn'].forEach(id=>{const b=$('#'+id); if(b)b.addEventListener('click',openNewQa);});
['newVariationBtn','newVariationTopBtn'].forEach(id=>{const b=$('#'+id); if(b)b.addEventListener('click',openNewVariation);});
['newLabourBtn','newLabourTopBtn'].forEach(id=>{const b=$('#'+id); if(b)b.addEventListener('click',openNewLabour);});
$('#cancelQaBtn')?.addEventListener('click',()=>hidePanel('#qaFormPanel'));
$('#cancelVariationBtn')?.addEventListener('click',()=>hidePanel('#variationFormPanel'));
$('#cancelLabourBtn')?.addEventListener('click',()=>hidePanel('#labourFormPanel'));
$('#saveQaBtn')?.addEventListener('click',()=>{state.qaRecords.unshift({date:$('#qaDate').value||today(),block:$('#qaBlock').value,floor:$('#qaFloor').value,area:$('#qaArea').value,type:$('#qaType').value,status:$('#qaStatus').value,comments:$('#qaComments').value}); ['qaBlock','qaFloor','qaArea','qaComments'].forEach(id=>$('#'+id).value=''); save(); renderModuleRecords(); hidePanel('#qaFormPanel');});
function variationTotal(){const labour=Number($('#varLabour')?.value||0),materials=Number($('#varMaterials')?.value||0),plant=Number($('#varPlant')?.value||0),margin=Number($('#varMargin')?.value||0);const sub=labour+materials+plant; return sub+(sub*margin/100);}
$('#saveVariationBtn')?.addEventListener('click',()=>{state.variationRecords.unshift({date:$('#varDate').value||today(),no:$('#varNo').value,project:$('#varProject').value,description:$('#varDescription').value,status:$('#varStatus').value,total:variationTotal()}); ['varDescription'].forEach(id=>$('#'+id).value=''); save(); renderModuleRecords(); hidePanel('#variationFormPanel');});
function populateLabourOperatives(){const sel=$('#labOperative'); if(!sel)return; sel.innerHTML='<option value="">Select operative</option>'+state.operatives.map(o=>`<option value="${escapeHtml(o.name)}">${escapeHtml(o.name)}</option>`).join('');}
$('#labOperative')?.addEventListener('change',e=>{const op=state.operatives.find(o=>o.name===e.target.value); if(op){$('#labCompany').value=op.company; $('#labTrade').value=op.trade;}});
function calcHours(start,end,breakMin){if(!start||!end)return 0; const [sh,sm]=start.split(':').map(Number),[eh,em]=end.split(':').map(Number); let mins=(eh*60+em)-(sh*60+sm)-Number(breakMin||0); if(mins<0)mins+=1440; return Math.max(0,mins/60);}
$('#saveLabourBtn')?.addEventListener('click',()=>{const hours=calcHours($('#labTimeIn').value,$('#labTimeOut').value,$('#labBreak').value);state.labourRecords.unshift({date:$('#labDate').value||today(),operative:$('#labOperative').value,company:$('#labCompany').value,trade:$('#labTrade').value,time:`${$('#labTimeIn').value||''} - ${$('#labTimeOut').value||''}`,hours,area:$('#labArea').value,notes:$('#labNotes').value}); ['labTimeIn','labTimeOut','labArea','labNotes'].forEach(id=>$('#'+id).value=''); save(); renderModuleRecords(); hidePanel('#labourFormPanel');});
function badgeClass(status){return String(status||'').toLowerCase().replace(/[^a-z]/g,'')}
function renderModuleRecords(){
 const qb=$('#qaRecordsBody'); if(qb)qb.innerHTML=(state.qaRecords||[]).map(r=>`<tr><td>${esc(r.date)}</td><td>${esc(r.block)}</td><td>${esc(r.floor)}</td><td>${esc(r.area)}</td><td>${esc(r.type)}</td><td><span class="status-badge ${badgeClass(r.status)}">${esc(r.status)}</span></td><td>${esc(r.comments)}</td></tr>`).join('')||'<tr><td colspan="7">No QA records yet. Press New QA.</td></tr>';
 const vb=$('#variationRecordsBody'); if(vb)vb.innerHTML=(state.variationRecords||[]).map(r=>`<tr><td>${esc(r.date)}</td><td>${esc(r.no)}</td><td>${esc(r.project)}</td><td>${esc(r.description)}</td><td><span class="status-badge ${badgeClass(r.status)}">${esc(r.status)}</span></td><td>£${Number(r.total||0).toFixed(2)}</td></tr>`).join('')||'<tr><td colspan="6">No variations yet. Press New Variation.</td></tr>';
 const lb=$('#labourRecordsBody'); if(lb)lb.innerHTML=(state.labourRecords||[]).map(r=>`<tr><td>${esc(r.date)}</td><td>${esc(r.operative)}</td><td>${esc(r.company)}</td><td>${esc(r.trade)}</td><td>${esc(r.time)}</td><td>${Number(r.hours||0).toFixed(2)}</td><td>${esc(r.area)}</td></tr>`).join('')||'<tr><td colspan="7">No labour records yet. Press New Labour Entry.</td></tr>';
}

function buildPdf(type='daily'){const date=$('#briefDate').value||today();const rows=state.rows.filter(r=>r.name||r.signature);const title=type==='monthly'?'Monthly Attendance and Briefing Report':'Daily Start Briefing';const monthLabel=new Date(date).toLocaleDateString('en-GB',{month:'long',year:'numeric'});$('#pdfDocument').innerHTML=`<div class="pdf-page"><div class="pdf-header"><img src="logo.jpg"><div class="pdf-title"><h1>${title}</h1><p>${type==='monthly'?monthLabel:date}</p></div><div class="pdf-meta"><b>Doc No:</b> ${esc($('#docNo').value)}<br><b>Date:</b> ${esc(date)}<br><b>Generated:</b> ${new Date().toLocaleString('en-GB')}</div></div><div class="pdf-box-grid"><div class="pdf-box"><b>Project Name</b>${esc($('#projectName').value)}</div><div class="pdf-box"><b>Main Contractor</b>${esc($('#mainContractor').value)}</div><div class="pdf-box"><b>Site Address</b>${esc($('#siteAddress').value)}</div><div class="pdf-box"><b>Site Manager</b>${esc($('#siteManager').value)}</div></div><div class="pdf-box-grid"><div class="pdf-box"><b>Planned Activities</b>${esc($('#plannedActivities').value)}</div><div class="pdf-box"><b>Location / Area</b>${esc($('#locationArea').value)}</div><div class="pdf-box"><b>Health & Safety Briefing</b>${esc($('#hsBriefing').value)}</div><div class="pdf-box"><b>Deliveries / Plant / Permits</b>${esc($('#deliveries').value)}</div></div><div class="pdf-section-title">Operative Attendance and Digital Signatures</div><table class="pdf-table"><thead><tr><th style="width:8mm">No.</th><th>Operative Name</th><th>Company</th><th>Trade</th><th>CSCS No.</th><th>Time In</th><th style="width:48mm">Signature</th></tr></thead><tbody>${rows.map((r,i)=>`<tr class="no-print-break"><td>${i+1}</td><td>${esc(r.name)}</td><td>${esc(r.company)}</td><td>${esc(r.trade)}</td><td>${esc(r.cscs)}</td><td>${esc(r.time)}</td><td>${r.signature?`<img class="sig-img" src="${r.signature}">`:'Not signed'}</td></tr>`).join('')||'<tr><td colspan="7">No operatives added.</td></tr>'}</tbody></table><div class="pdf-section-title">Site Manager Sign Off</div><div class="pdf-sign-box"></div><div class="pdf-footer"><span>NCP Mechanical LTD · Generated by NCP Mechanical Pro Portal</span><span>Page 1</span></div></div>`;}
$('#dailyPdfBtn').addEventListener('click',()=>{buildPdf('daily');window.print();});$('#monthlyPdfBtn').addEventListener('click',()=>{buildPdf('monthly');window.print();});$('#previewPdfBtn').addEventListener('click',()=>{buildPdf('daily');alert('PDF layout is ready. Press Daily PDF Export and choose Save as PDF.');});
function esc(v){return String(v||'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m])).replace(/\n/g,'<br>')}function escapeHtml(v){return String(v||'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').hidden=false;});$('#installBtn').addEventListener('click',async()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null;$('#installBtn').hidden=true;}});
if('serviceWorker' in navigator){navigator.serviceWorker.getRegistrations().then(rs=>rs.forEach(r=>r.unregister())).catch(()=>{});}init();
